defmodule Mix.Tasks.Bumpver.Git.Install do
  @moduledoc """
  Installs a Git hook which runs a Mix task.

  Git hooks are local to a clone and are not checked into version control.

  By default this installs the `pre-commit` hook to run `mix bumpver.check`.

  ## Usage

      mix bumpver.git.install

  ## Options

    * `--hook HOOK` - Hook name (default: `pre-commit`)
    * `--command CMD` - Mix command to run (default: `bumpver.check`)
    * `--auto-bump` - If `--command` is `bumpver.check`, add `--auto-bump` (interactive by default)
    * `--bump TYPE` - One of: major, minor, patch (implies non-interactive when combined with `--auto-bump`)
    * `--major|--minor|--patch` - Convenience aliases for `--bump`
    * `--yes` - Pass `--yes` to `mix bumpver.check` (non-interactive; uses patch if no type given)
    * `--force` - Overwrite existing hook

  ## Examples

      # Install (or update) the default pre-commit hook
      mix bumpver.git.install

      # Use your alias task
      mix bumpver.git.install --command precommit

      # Install for a different hook
      mix bumpver.git.install --hook pre-push --command "test"

      # Auto-bump when bumpver.check fails (interactive by default)
      mix bumpver.git.install --auto-bump
      mix bumpver.git.install --auto-bump --bump minor
  """

  use Mix.Task

  alias Bumpver.{CLIArgs, Git}

  @shortdoc "Install a git hook for bumpver"

  @requirements ["loadpaths"]

  @doc false
  def run(args) do
    {opts, _rest, invalid} =
      OptionParser.parse(args,
        strict: [
          hook: :string,
          command: :string,
          auto_bump: :boolean,
          bump: :string,
          major: :boolean,
          minor: :boolean,
          patch: :boolean,
          yes: :boolean,
          force: :boolean,
          help: :boolean
        ]
      )

    if invalid != [] do
      Mix.raise("Invalid options: #{inspect(invalid)}")
    end

    if opts[:help] do
      Mix.shell().info(help_text())
      :ok
    else
      hook_name = opts[:hook] || "pre-commit"
      command = command_from_opts!(opts)
      force? = opts[:force] || false

      hooks_dir = git_hooks_dir!()
      File.mkdir_p!(hooks_dir)

      hook_path = Path.join(hooks_dir, hook_name)

      desired = hook_script(command)

      cond do
        File.exists?(hook_path) and File.read!(hook_path) == desired ->
          Mix.shell().info("✓ Git hook already installed: #{hook_path}")
          Mix.shell().info("  Runs: mix #{command}")
          :ok

        File.exists?(hook_path) and not force? ->
          Mix.raise(
            "Hook already exists at #{hook_path} (different content). Re-run with --force to overwrite."
          )

        true ->
          File.write!(hook_path, desired)
          chmod_executable(hook_path)

          Mix.shell().info("✓ Installed git hook: #{hook_path}")
          Mix.shell().info("  Runs: mix #{command}")
          :ok
      end
    end
  end

  defp command_from_opts!(opts) do
    base = opts[:command] || "bumpver.check"
    base = String.trim(base)

    if opts[:auto_bump] do
      ensure_bumpver_check_command!(base)

      bump_type =
        case Bumpver.bump_type_from_opts(opts) do
          {:ok, type} -> type
          {:error, msg} -> Mix.raise(msg)
        end

      extra_args =
        ["--auto-bump"] ++
          Bumpver.version_check_args_for_type(bump_type) ++
          CLIArgs.yes_args(opts)

      Enum.join([base | extra_args], " ")
    else
      base
    end
  end

  defp ensure_version_check_command!(command) do
    first = command |> String.split() |> List.first()

    if first != "bumpver.check" do
      Mix.raise("--auto-bump can only be used when --command starts with bumpver.check")
    end
  end

  defp ensure_bumpver_check_command!(command), do: ensure_version_check_command!(command)

  defp git_hooks_dir!, do: Git.hooks_dir!()

  defp hook_script(command) do
    command = String.trim(command)

    """
    #!/bin/sh
    # Generated by `mix bumpver.git.install`
    set -e

    mix #{command}
    """
  end

  defp chmod_executable(path) do
    try do
      File.chmod!(path, 0o755)
    rescue
      _ -> :ok
    end
  end

  defp help_text do
    """
    mix bumpver.git.install - install a git hook to run a Mix command

    Usage:
      mix bumpver.git.install
      mix bumpver.git.install --command precommit
      mix bumpver.git.install --hook pre-push --command "test"
      mix bumpver.git.install --auto-bump
      mix bumpver.git.install --auto-bump --bump minor

    Options:
      --hook HOOK        Hook name (default: pre-commit)
      --command CMD      Mix command to run (default: bumpver.check)
      --auto-bump         For bumpver.check only: adds --auto-bump (interactive by default)
      --bump TYPE         For auto-bump: major|minor|patch
      --major             Alias for --bump major
      --minor             Alias for --bump minor
      --patch             Alias for --bump patch
      --yes               For auto-bump: non-interactive (uses patch if no type given)
      --force            Overwrite existing hook
      --help             Show this help
    """
  end
end
