defmodule Mix.Tasks.Bumpver.Git.Uninstall do
  @moduledoc """
  Uninstalls a Git hook previously installed by bumpver.

  This is intentionally conservative:

  * If the hook file does not exist, this task succeeds (idempotent).
  * If the hook exists but does not look like it was generated by bumpver,
    this task refuses unless `--force` is provided.

  ## Usage

      mix bumpver.git.uninstall

  ## Options

    * `--hook HOOK` - Hook name (default: `pre-commit`)
    * `--force` - Remove the hook even if it wasn't generated by bumpver

  ## Examples

      mix bumpver.git.uninstall
      mix bumpver.git.uninstall --hook pre-push
      mix bumpver.git.uninstall --force
  """

  use Mix.Task

  alias Bumpver.Git

  @shortdoc "Uninstall a bumpver git hook"

  @requirements ["loadpaths"]

  @doc false
  def run(args) do
    {opts, _rest, invalid} =
      OptionParser.parse(args,
        strict: [
          hook: :string,
          force: :boolean,
          help: :boolean
        ]
      )

    if invalid != [] do
      Mix.raise("Invalid options: #{inspect(invalid)}")
    end

    if opts[:help] do
      Mix.shell().info(help_text())
      :ok
    else
      hook_name = opts[:hook] || "pre-commit"
      force? = opts[:force] || false

      hooks_dir = git_hooks_dir!()
      hook_path = Path.join(hooks_dir, hook_name)

      cond do
        not File.exists?(hook_path) ->
          Mix.shell().info("✓ Git hook already removed: #{hook_path}")
          :ok

        force? ->
          File.rm!(hook_path)
          Mix.shell().info("✓ Removed git hook: #{hook_path}")
          :ok

        generated_by_bumpver?(hook_path) ->
          File.rm!(hook_path)
          Mix.shell().info("✓ Removed git hook: #{hook_path}")
          :ok

        true ->
          Mix.raise(
            "Refusing to remove #{hook_path} because it doesn't look like it was generated by bumpver. Re-run with --force to remove it anyway."
          )
      end
    end
  end

  defp generated_by_bumpver?(hook_path) do
    case File.read(hook_path) do
      {:ok, content} ->
        String.contains?(content, "# Generated by `mix bumpver.git.install`")

      _ ->
        false
    end
  end

  defp git_hooks_dir! do
    Git.hooks_dir!()
  end

  defp help_text do
    """
    mix bumpver.git.uninstall - uninstall a bumpver-installed git hook

    Usage:
      mix bumpver.git.uninstall
      mix bumpver.git.uninstall --hook pre-push

    Options:
      --hook HOOK        Hook name (default: pre-commit)
      --force            Remove even if not generated by bumpver
      --help             Show this help
    """
  end
end
